# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
   secret_key_base: edfa828956fe8017c7d536592c50bf76e5b16ac47c87bb80a1ed18fbaafc40af029b23a172f422b2483e1f81056eca4d233dedb5c09f16322d95fad2468b97ce

test:
  secret_key_base: 1da6b80ac97718f54175cd3ec6e5dccf7607f3afb7b8f154b976aa80a02545a8637e34db4faaf9197d38cd86c484e521e4d3bed36858edf50d1bb1ffc086c941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

#example from stripe github
# development:
#   secret_key_base: __RAILS_SECRET
#   stripe_publishable_key: __STRIPE_PUBLISHABLE
#   stripe_secret_key: __STRIPE_SECRET
#   stripe_client_id: __STRIPE_CLIENT
#   fee_percentage: 0.1
